# Generated by Django 2.2.5 on 2019-09-12 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='acquired_date',
            new_name='Issue_date',
        ),
        migrations.RemoveField(
            model_name='items',
            name='Due_date',
        ),
        migrations.AddField(
            model_name='items',
            name='Device',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tickets',
            name='items',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ts.Items'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ts.Customer'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ts.Customer'),
        ),
    ]
