# Generated by Django 2.2.5 on 2019-09-12 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0002_auto_20190912_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='Issue_date',
        ),
        migrations.AddField(
            model_name='items',
            name='Item_Id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='items',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ts.Items'),
        ),
    ]
