# Generated by Django 2.2.5 on 2019-09-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0003_auto_20190912_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Item_Id',
            field=models.IntegerField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='items',
            field=models.ForeignKey(blank=True, default='Items_Id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ts.Items'),
        ),
    ]
